### ISSUE TITLE
[Bug] Try to use but get error

### ISSUE THREAD

**Issue by ChaoKuan-Lin** [acksin/hubspot#1]
Try to use hubspot-go in our service
but when I test hubspot this package
It case panic and show this information

![2016-11-16 11 47 04](https://cloud.githubusercontent.com/assets/1070832/20353875/28596460-ac57-11e6-839f-2cc040353fb5.png)

My code is same as you write

![2016-11-16 11 50 17](https://cloud.githubusercontent.com/assets/1070832/20353961/8c8fa426-ac57-11e6-98a5-2011406c77fb.png)

**Comment by Fyb3roptik** [comment]
Check out my fork. It is working:

https://github.com/Fyb3roptik/hubspot
